DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence START WITH 1000 INCREMENT BY 1;
--SKILLS
INSERT INTO SKILL (ID,NAME) VALUES (1,'UX');
INSERT INTO SKILL (ID,NAME) VALUES (2,'HTML5');
INSERT INTO SKILL (ID,NAME) VALUES (3,'CSS');
INSERT INTO SKILL (ID,NAME) VALUES (4,'Web Design');
INSERT INTO SKILL (ID,NAME) VALUES (5,'PHP');
INSERT INTO SKILL (ID,NAME) VALUES (6,'Java');
INSERT INTO SKILL (ID,NAME) VALUES (7,'AngularJS');
INSERT INTO SKILL (ID,NAME) VALUES (8,'jQuery');
--ROLES
INSERT INTO ROLE (ID, DESCRIPTION) VALUES (1,'Desenvolvedor Java');
INSERT INTO ROLE (ID, DESCRIPTION) VALUES (2,'Tester');
INSERT INTO ROLE (ID, DESCRIPTION) VALUES (3,'Analista de Requisitos');
--DEPARTMENTS
INSERT INTO DEPARTMENT (ID, NAME) VALUES (1,'Escritorio de Inovacoes');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2,'Cliente Externo');
--USER DEFAULT
INSERT INTO USER (ID, USERNAME, PASSWORD, NAME) VALUES (1, 'admin' , '21232f297a57a5a743894a0e4a801fc3', 'Administrador');
